### ISSUE TITLE
Undefined property: stdClass::$base

### ISSUE THREAD

**Issue by stevangd** [benmajor/ExchangeRatesAPI#7]
Just had an issue here, i think its related to the Endpoint Response?

**How to produce the error**
```
        $lookup = new ExchangeRatesAPI();
        $rates  = $lookup->addRate('USD')->setBaseCurrency('SGD')->fetch();
        $rate = $rates->getRates();
        echo $rate;
```

**Screenshoot**
![image](https://user-images.githubusercontent.com/78889847/113274309-bffcc500-9307-11eb-8fbc-2f9bde828224.png)

**Libraries Used**
"guzzlehttp/guzzle": "^6.4"
"benmajor/exchange-rates-api": "^1.0"
"php": "^7.1.3"

**Comment by benmajor** [comment]
Thanks, this seems to be related to recent changes to the API (please see https://github.com/benmajor/ExchangeRatesAPI/issues/8).

I'm investigating!

**Comment by ghost** [comment]
Just got the same error "Undefined property: stdClass::$base"

The api was working well when I first installed it and all conversions were working, this was last monday.
today, only 3 days later, I'm getting this error.

I checked out #8 and changed to exchangerate.host api key, but still getting this issue.

![Screenshot 2023-09-28 at 5 38 11 PM](https://github.com/benmajor/ExchangeRatesAPI/assets/136681487/35fdfafb-36de-48d3-8d7f-c76e39f0770a)

code being used:
use \BenMajor\ExchangeRatesAPI\ExchangeRatesAPI;
use \BenMajor\ExchangeRatesAPI\Response;
use \BenMajor\ExchangeRatesAPI\Exception;


$access_key = '************';
$use_ssl = false; 

$lookup = new ExchangeRatesAPI($access_key, $use_ssl);
$rates  = $lookup->addRate('EUR')->setBaseCurrency('USD')->fetch();

as I mentioned, this was working for me at the start of the week, nothing was changed since then. now its bricked.

**Comment by benmajor** [comment]
That looks like a PHP notice that is being triggered, and then caught in your `try catch` block. Did you (or your host) change PHP versions or settings in the last week? Disabling notices should be sufficient to get this back online until I can take a look.

**Comment by ghost** [comment]
> That looks like a PHP notice that is being triggered, and then caught in your `try catch` block. Did you (or your host) change PHP versions or settings in the last week? Disabling notices should be sufficient to get this back online until I can take a look.

PHP versions have not been changed or anything else for that matter, I'll disable the notices and see if that resolves anything.

Edit: Disabling the notice gives a 500 page instead and throws the same error to the logs instead.

**Comment by benmajor** [comment]
@TalalHena this looks like an update from the API's side that bricked the SDK. Please update to `4.2.0`:
https://packagist.org/packages/benmajor/exchange-rates-api#4.2.0
